2021-12-27 20:15:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "BOND" не найдена
Table "BOND" not found; SQL statement:
SELECT * FROM BOND WHERE ticker = 'SBER'  [42102-200]
2021-12-28 07:51:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "BOND" не найдена
Table "BOND" not found; SQL statement:
SELECT * FROM BOND  [42102-200]
2021-12-28 07:52:57 jdbc[19]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "BOND" не найдена
Table "BOND" not found; SQL statement:
SELECT * FROM BOND  [42102-200]
2021-12-28 07:52:58 jdbc[40]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "BOND" не найдена
Table "BOND" not found; SQL statement:
UPDATE BOND SET name = '', short_name = '', lat_name = '', nominal = 90.000000, nominal_value = 'RUB', issue_date = '2021-12-28', isin = 'qwer', issue_size = 90, market_type = 'BONDS', type = 'CB', mat_date = '', coupon = 0.000000, day_to_redemption = 0 WHERE ticker = 'SQFWQDQ'  [42102-200]
2021-12-28 07:53:00 jdbc[7]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "BOND" не найдена
Table "BOND" not found; SQL statement:
SELECT * FROM BOND  [42102-200]
2021-12-28 07:53:00 jdbc[12]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:100)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:74)
	at ru.sfedu.api.DataProviderJdbc.getMarkets(DataProviderJdbc.java:173)
	at ru.sfedu.api.DataProviderJdbc.appendOrUpdateMarket(DataProviderJdbc.java:149)
	at ru.sfedu.api.DataProviderJdbc.appendSecurity(DataProviderJdbc.java:299)
	at ru.sfedu.api.DataProviderJdbc.appendStocks(DataProviderJdbc.java:603)
	at ru.sfedu.api.DataProviderJdbcTest.testGetSecurityByTicker(DataProviderJdbcTest.java:1133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

org.h2.message.DbException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.creatingTable(DataProviderJdbc.java:87)
	at ru.sfedu.api.DataProviderJdbc.creatingTable(DataProviderJdbc.java:111)
	at ru.sfedu.api.DataProviderJdbc.appendSecurity(DataProviderJdbc.java:286)
	at ru.sfedu.api.DataProviderJdbc.appendBonds(DataProviderJdbc.java:634)
	at ru.sfedu.api.DataProviderJdbcTest.testGetSecurityByTicker(DataProviderJdbcTest.java:1134)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 33 more
2021-12-28 07:53:00 jdbc[12]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:100)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryDBConnection(DataProviderJdbc.java:721)
	at ru.sfedu.api.DataProviderJdbc.appendOrUpdateSecurityHistory(DataProviderJdbc.java:886)
	at ru.sfedu.api.DataProviderJdbc.appendSecurity(DataProviderJdbc.java:296)
	at ru.sfedu.api.DataProviderJdbc.appendStocks(DataProviderJdbc.java:603)
	at ru.sfedu.api.DataProviderJdbcTest.testGetSecurityByTicker(DataProviderJdbcTest.java:1133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

org.h2.message.DbException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.creatingTable(DataProviderJdbc.java:87)
	at ru.sfedu.api.DataProviderJdbc.creatingTable(DataProviderJdbc.java:111)
	at ru.sfedu.api.DataProviderJdbc.appendSecurity(DataProviderJdbc.java:286)
	at ru.sfedu.api.DataProviderJdbc.appendBonds(DataProviderJdbc.java:634)
	at ru.sfedu.api.DataProviderJdbcTest.testGetSecurityByTicker(DataProviderJdbcTest.java:1134)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 33 more
2021-12-28 07:53:00 jdbc[12]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:100)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryDBConnection(DataProviderJdbc.java:721)
	at ru.sfedu.api.DataProviderJdbc.appendOrUpdateSecurityHistory(DataProviderJdbc.java:886)
	at ru.sfedu.api.DataProviderJdbc.appendSecurity(DataProviderJdbc.java:296)
	at ru.sfedu.api.DataProviderJdbc.appendStocks(DataProviderJdbc.java:603)
	at ru.sfedu.api.DataProviderJdbcTest.testGetSecurityByTicker(DataProviderJdbcTest.java:1133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

org.h2.message.DbException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.creatingTable(DataProviderJdbc.java:87)
	at ru.sfedu.api.DataProviderJdbc.creatingTable(DataProviderJdbc.java:111)
	at ru.sfedu.api.DataProviderJdbc.appendSecurity(DataProviderJdbc.java:286)
	at ru.sfedu.api.DataProviderJdbc.appendBonds(DataProviderJdbc.java:634)
	at ru.sfedu.api.DataProviderJdbcTest.testGetSecurityByTicker(DataProviderJdbcTest.java:1134)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 33 more
2021-12-28 07:53:00 jdbc[12]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:100)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryDBConnection(DataProviderJdbc.java:721)
	at ru.sfedu.api.DataProviderJdbc.appendOrUpdateSecurityHistory(DataProviderJdbc.java:886)
	at ru.sfedu.api.DataProviderJdbc.appendSecurity(DataProviderJdbc.java:296)
	at ru.sfedu.api.DataProviderJdbc.appendStocks(DataProviderJdbc.java:603)
	at ru.sfedu.api.DataProviderJdbcTest.testGetSecurityByTicker(DataProviderJdbcTest.java:1133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

org.h2.message.DbException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.creatingTable(DataProviderJdbc.java:87)
	at ru.sfedu.api.DataProviderJdbc.creatingTable(DataProviderJdbc.java:111)
	at ru.sfedu.api.DataProviderJdbc.appendSecurity(DataProviderJdbc.java:286)
	at ru.sfedu.api.DataProviderJdbc.appendBonds(DataProviderJdbc.java:634)
	at ru.sfedu.api.DataProviderJdbcTest.testGetSecurityByTicker(DataProviderJdbcTest.java:1134)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 33 more
2021-12-28 07:53:00 jdbc[12]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:100)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryDBConnection(DataProviderJdbc.java:721)
	at ru.sfedu.api.DataProviderJdbc.appendOrUpdateSecurityHistory(DataProviderJdbc.java:886)
	at ru.sfedu.api.DataProviderJdbc.appendSecurity(DataProviderJdbc.java:296)
	at ru.sfedu.api.DataProviderJdbc.appendStocks(DataProviderJdbc.java:603)
	at ru.sfedu.api.DataProviderJdbcTest.testGetSecurityByTicker(DataProviderJdbcTest.java:1133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

org.h2.message.DbException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.creatingTable(DataProviderJdbc.java:87)
	at ru.sfedu.api.DataProviderJdbc.creatingTable(DataProviderJdbc.java:111)
	at ru.sfedu.api.DataProviderJdbc.appendSecurity(DataProviderJdbc.java:286)
	at ru.sfedu.api.DataProviderJdbc.appendBonds(DataProviderJdbc.java:634)
	at ru.sfedu.api.DataProviderJdbcTest.testGetSecurityByTicker(DataProviderJdbcTest.java:1134)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 33 more
2021-12-28 07:53:00 jdbc[12]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:100)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.getSecurityHistoryDBConnection(DataProviderJdbc.java:721)
	at ru.sfedu.api.DataProviderJdbc.appendOrUpdateSecurityHistory(DataProviderJdbc.java:886)
	at ru.sfedu.api.DataProviderJdbc.appendSecurity(DataProviderJdbc.java:296)
	at ru.sfedu.api.DataProviderJdbc.appendStocks(DataProviderJdbc.java:603)
	at ru.sfedu.api.DataProviderJdbcTest.testGetSecurityByTicker(DataProviderJdbcTest.java:1133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

org.h2.message.DbException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.sfedu.api.DataProviderJdbc.getDbConnection(DataProviderJdbc.java:39)
	at ru.sfedu.api.DataProviderJdbc.creatingTable(DataProviderJdbc.java:87)
	at ru.sfedu.api.DataProviderJdbc.creatingTable(DataProviderJdbc.java:111)
	at ru.sfedu.api.DataProviderJdbc.appendSecurity(DataProviderJdbc.java:286)
	at ru.sfedu.api.DataProviderJdbc.appendBonds(DataProviderJdbc.java:634)
	at ru.sfedu.api.DataProviderJdbcTest.testGetSecurityByTicker(DataProviderJdbcTest.java:1134)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 33 more
2021-12-28 07:53:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "BOND" не найдена
Table "BOND" not found; SQL statement:
SELECT * FROM BOND  [42102-200]
2021-12-28 07:53:01 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "BOND" не найдена
Table "BOND" not found; SQL statement:
SELECT * FROM BOND  [42102-200]
2021-12-28 07:53:01 jdbc[5]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "BOND" не найдена
Table "BOND" not found; SQL statement:
SELECT * FROM BOND  [42102-200]
2021-12-28 07:53:02 jdbc[15]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "BOND" не найдена
Table "BOND" not found; SQL statement:
SELECT * FROM BOND  [42102-200]
2021-12-28 07:53:02 jdbc[16]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "BOND" не найдена
Table "BOND" not found; SQL statement:
SELECT * FROM BOND  [42102-200]
2021-12-28 07:53:02 jdbc[17]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "BOND" не найдена
Table "BOND" not found; SQL statement:
SELECT * FROM BOND  [42102-200]
2021-12-28 07:53:02 jdbc[18]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "BOND" не найдена
Table "BOND" not found; SQL statement:
SELECT * FROM BOND  [42102-200]
2021-12-28 07:53:02 jdbc[42]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "BOND" не найдена
Table "BOND" not found; SQL statement:
SELECT * FROM BOND WHERE ticker = 'SBER'  [42102-200]
2021-12-28 07:53:02 jdbc[43]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "BOND" не найдена
Table "BOND" not found; SQL statement:
SELECT * FROM BOND WHERE ticker = 'SBERBOND'  [42102-200]
2021-12-28 07:53:02 jdbc[54]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "BOND" не найдена
Table "BOND" not found; SQL statement:
SELECT * FROM BOND WHERE ticker = 'SBER'  [42102-200]
2021-12-28 07:53:02 jdbc[55]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "BOND" не найдена
Table "BOND" not found; SQL statement:
SELECT * FROM BOND WHERE ticker = 'SBER'  [42102-200]
2021-12-28 07:53:02 jdbc[56]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "BOND" не найдена
Table "BOND" not found; SQL statement:
SELECT * FROM BOND  [42102-200]
2021-12-28 07:53:02 jdbc[57]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "BOND" не найдена
Table "BOND" not found; SQL statement:
SELECT * FROM BOND  [42102-200]
2021-12-28 07:53:03 jdbc[65]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "BOND" не найдена
Table "BOND" not found; SQL statement:
SELECT * FROM BOND WHERE ticker = 'SBERBOND'  [42102-200]
2021-12-28 07:53:03 jdbc[115]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "BOND" не найдена
Table "BOND" not found; SQL statement:
SELECT * FROM BOND  [42102-200]
2021-12-28 07:53:03 jdbc[128]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "BOND" не найдена
Table "BOND" not found; SQL statement:
SELECT * FROM BOND  [42102-200]
2021-12-28 07:53:03 jdbc[129]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "BOND" не найдена
Table "BOND" not found; SQL statement:
SELECT * FROM BOND  [42102-200]
2021-12-28 07:53:03 jdbc[130]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "BOND" не найдена
Table "BOND" not found; SQL statement:
SELECT * FROM BOND  [42102-200]
2021-12-28 07:53:03 jdbc[131]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "BOND" не найдена
Table "BOND" not found; SQL statement:
SELECT * FROM BOND  [42102-200]
2021-12-28 07:53:03 jdbc[132]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "BOND" не найдена
Table "BOND" not found; SQL statement:
SELECT * FROM BOND  [42102-200]
